CREATE DATABASE Origem;
GO
USE Origem;
GO
CREATE TABLE TB_EXEMPLO_ORIGEM (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  NOME VARCHAR(100),
  ATUALIZADO_EM DATETIME DEFAULT GETDATE()
);
GO
INSERT INTO TB_EXEMPLO_ORIGEM (NOME) VALUES ('João'), ('Maria'), ('Pedro');
GO



SELECT * FROM TB_EXEMPLO_ORIGEM;
